export const WEATHER = [
    {
        id: 1,
        city: 'Hamburg',
        todayTemp: '12',
        todayTempMin: '9',
        todayTempMax: '13',
        todayRain: 'y',
        seven_DaysTemp: '11',
        seven_DaysTempMin: '10',
        seven_DaysTempMax: '11',
        seven_DaysRain: 'n',
    },
    {
        id: 2,
        city: 'Rom',
        todayTemp: '15',
        todayTempMin: '12',
        todayTempMax: '16',
        todayRain: 'n',
        seven_DaysTemp: '13',
        seven_DaysTempMin: '13',
        seven_DaysTempMax: '15',
        seven_DaysRain: 'n',
    }, {
        id: 3,
        city: 'Paris',
        todayTemp: '13',
        todayTempMin: '8',
        todayTempMax: '13',
        todayRain: 'y',
        seven_DaysTemp: '7',
        seven_DaysTempMin: '5',
        seven_DaysTempMax: '7',
        seven_DaysRain: 'y',
    }
]